gomin-solution/Backend

- controllers/choice.controller.js
- services/choice.service.js
> [chore] 투표 불러오기시 비율로 변경

- controllers/choice.controller.js
- controllers/comment.controller.js
- package-lock.json
- package.json
- services/choice.service.js
> [chore] choice값 비율로 변경

- controllers/advice.controller.js
- repositories/advice.repository.js
- routes/advice.routes.js
- services/advice.service.js
> [chore] 조언게시글 페이지 추가

- controllers/advice.controller.js
> [chore] 조언 게시물 페이징 수정

- controllers/choice.controller.js
> [chore] 시작번호 1에서 0으로 변경

- controllers/choice.controller.js
> [chore] null 제거

- controllers/note.controller.js
- repositories/note.repository.js
- routes/note.routes.js
- services/note.service.js
> [feat] 쪽지삭제 추가

- app.js
- controllers/advice.controller.js
- repositories/advice.repository.js
- routes/advice.routes.js
- schemas/adviceReport.js
- services/advice.service.js
- util/schedule.js
> [feat] 조언 게시글 신고

- services/advice.service.js
- util/schedule.js
> [chore] 조언 상세페이지 조회수

- controllers/choice.controller.js
- controllers/comment.controller.js
- repositories/comment.repository.js
- schemas/report.js
- services/choice.service.js
- services/comment.service.js
- test/choice.test.js
> 신고 및 쵸이스 기능 개선

- controllers/manager.controller.js
- repositories/comment.repository.js
- repositories/manager.repository.js
- services/manager.service.js
> [feat] 신고기능 개선

- migrations/addcolumn.js
> merge test

- controllers/advice.controller.js
- repositories/advice.repository.js
- routes/advice.routes.js
- services/advice.service.js
> [chore] 조언게시물 요청수정

- controllers/advice.controller.js
- routes/advice.routes.js
- services/advice.service.js
> [chore] 조언 게시물 필터정렬

- controllers/choice.controller.js
- migrations/01-create-user.js
- repositories/choice.repository.js
- routes/choice.routes.js
- services/choice.service.js
> [feat] 정렬 및 조기 종료

- controllers/advice.controller.js
- repositories/advice.repository.js
- routes/user.routes.js
- services/advice.service.js
> [chore] 조언 수정,삭제 수정

- controllers/advice.controller.js
- controllers/user.controller.js
- repositories/advice.repository.js
- repositories/users.repository.js
- services/advice.service.js
- services/users.service.js
> [chore] 코드 다이어트 추가

- controllers/comment.controller.js
- migrations/05-01-create-reply.js
- models/reply.js
- repositories/comment.repository.js
- routes/comment.routes.js
- services/comment.service.js
> [feat] 대댓글 기능

- modules/advice.multer.js
- services/advice.service.js
- services/users.service.js
> [chore] 유저이미지 수정

- controllers/comment.controller.js
- controllers/report.controller.js
- repositories/comment.repository.js
- repositories/manager.repository.js
- repositories/report.repository.js
- routes/comment.routes.js
- routes/index.routes.js
- routes/report.routes.js
- services/comment.service.js
- services/manager.service.js
- services/report.service.js
> 대댓글 및 신고기능 개선

- src/controllers/note.controller.js
- src/repositories/note.repository.js
- src/routes/note.routes.js
- src/services/note.service.js
> [feat] 쪽지방 삭제

- src/repositories/note.repository.js
> [feat] 쪽지방 삭제 변경

- src/migrations/16-2create-note.js
- src/models/note.js
> [chore] 케스케이드 수정

- src/controllers/comment.controller.js
- src/repositories/comment.repository.js
- src/services/comment.service.js
- src/test/choice.test.js
> [feat] 대댓글 삭제 수정

- src/controllers/comment.controller.js
- src/repositories/comment.repository.js
- src/services/comment.service.js
- src/test/choice.test.js
> [feat] 대댓글 기능 수정

- src/controllers/user.controller.js
- src/repositories/advice.repository.js
- src/repositories/choice.repository.js
- src/repositories/comment.repository.js
- src/services/users.service.js
> #218 메인페이지 고민마감수 수정

- src/repositories/mission.repository.js
- src/routes/choice.routes.js
- src/routes/comment.routes.js
- src/services/choice.service.js
- src/services/comment.service.js
> [chore] 미들웨어 붙임

- src/middlewares/rewardMiddleware.js
> [chore] 미들웨어에 에러코드 추가

- src/controllers/comment.controller.js
- src/services/comment.service.js
> [chore] 좋아요 기능 수정

- src/services/advice.service.js
- src/services/choice.service.js
- src/test/advice.test.js
- src/test/app.test.js
- src/test/choice.controller.test.js
- src/test/choice.test.js
> [test] 테스트 코드
